name: Build FitnessApp.ProfileApi image

on:
  push:
    branches:
    - master
    - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }} 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push develop
      if: github.ref == 'refs/heads/develop'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  
        build-args: |
          NUGET_PAT=${{ secrets.PACKAGE_SOURCE_PASSWORD }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitness-app-profile-api:alpha
        
    - name: Build and push latest
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  
        build-args: |
          NUGET_PAT=${{ secrets.PACKAGE_SOURCE_PASSWORD }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitness-app-profile-api:latest
